/**
 * Weekly Market Brief Generator
 * Transforms raw trend data into formatted insights
 */
import type { ProductTrend } from './trendEngine';

export interface MarketBrief {
    title: string;
    dateRange: string;
    summary: string;
    topCategories: string[];
    topProducts: string[];
    riskWarnings: string[];
    markdown: string;
}

export function generateMarketBrief(products: ProductTrend[]): MarketBrief {
    const topCategories = [...new Set(products.map(p => p.category))].slice(0, 3);
    const sorted = [...products].sort((a, b) => b.trendScore - a.trendScore);
    const topProducts = sorted.slice(0, 5).map(p => p.name);

    const date = new Date();
    const weekNum = Math.ceil(date.getDate() / 7);
    const monthName = date.toLocaleString('default', { month: 'long' });
    const title = `Vietnam Ecommerce Weekly Insight – ${monthName} Week ${weekNum}`;

    const summary = `This week, the Vietnam ecommerce landscape is dominated by ${topCategories[0]} and ${topCategories[1]}. We observed a significant spike in consumer interest for high-performance devices and seasonal beauty products.`;

    const riskWarnings = [
        'Logistics bottlenecks expected for imported goods due to regional shipping delays.',
        'Saturated competition in low-tier fashion segments.'
    ];

    // Generate Markdown
    const markdown = `
# ${title}

## Executive Summary
${summary}

## 🚀 Top Growing Categories
${topCategories.map(c => `- **${c}**`).join('\n')}

## 📦 Top 5 Trending Products
${sorted.slice(0, 5).map(p => `- ${p.name} (Trend Score: ${p.trendScore}, Growth: ${p.growthRate}%)`).join('\n')}

## ⚠️ Market Risks & Warnings
${riskWarnings.map(r => `- ${r}`).join('\n')}

---
*Generated by Vietnam Trend Radar AI*
  `.trim();

    return {
        title,
        dateRange: `${monthName} 2024`,
        summary,
        topCategories,
        topProducts,
        riskWarnings,
        markdown
    };
}
