/**
 * sampleSignalExample.ts
 *
 * A deterministic, ILLUSTRATIVE price series used to demonstrate the signal
 * engine end-to-end on the worked-example page. This is NOT a real ticker and
 * NOT live market data — it is a synthetic series generated by a fixed formula
 * so the build is reproducible and the methodology can be shown concretely.
 *
 * When a real OHLCV snapshot source is wired in (e.g. a committed snapshot from
 * the data pipeline, or a build-time fetch through a VN proxy), swap `SAMPLE_BARS`
 * for the real series and the same engine produces a real technical outlook.
 */
import type { OHLCBar, FundamentalInput } from '@utils/stockSignals';

const BAR_COUNT = 220; // ≈ 11 months of trading days
const BASE_TIME = 1_700_000_000; // fixed epoch seconds — no Date.now(), reproducible
const DAY = 86_400;

/**
 * Build a deterministic series: a gentle long-term uptrend with a couple of
 * cyclical swings and bounded, index-derived "noise" (no randomness). Shaped to
 * finish in a constructive-but-not-euphoric state so the example surfaces a
 * realistic mix of bullish and cautionary reasons.
 */
function buildBars(): OHLCBar[] {
  const bars: OHLCBar[] = [];
  for (let i = 0; i < BAR_COUNT; i++) {
    const trend = 20 + i * 0.06; // base uptrend from ~20.0
    const cycle = Math.sin(i / 18) * 1.6 + Math.sin(i / 47) * 2.4; // overlapping swings
    const noise = ((i * 73) % 11) / 11 - 0.5; // deterministic, bounded ±0.5
    const close = Number((trend + cycle + noise).toFixed(2));

    const open = Number((close - (((i * 31) % 7) / 7 - 0.5) * 0.6).toFixed(2));
    const high = Number((Math.max(open, close) + (((i * 17) % 5) / 5) * 0.5).toFixed(2));
    const low = Number((Math.min(open, close) - (((i * 23) % 5) / 5) * 0.5).toFixed(2));

    // Volume: a baseline with a deterministic spike near the end of the series.
    const spike = i === BAR_COUNT - 1 ? 2.6 : 1;
    const volume = Math.round((900_000 + ((i * 137) % 400_000)) * spike);

    bars.push({ t: BASE_TIME + i * DAY, o: open, h: high, l: low, c: close, v: volume });
  }
  return bars;
}

export const SAMPLE_TICKER = 'DEMO';

export const SAMPLE_BARS: OHLCBar[] = buildBars();

/** Illustrative fundamentals chosen to show a healthy-but-imperfect profile. */
export const SAMPLE_FUNDAMENTALS: FundamentalInput = {
  pe: 12.4,
  roe: 17.8,
  debtToEquity: 0.62,
  epsGrowth: 14.5,
  divYield: 3.1,
};
